// GENERATED by scripts/build-ev-models.mjs — do not edit by hand.
//
// Wait-shape counts for a seat that has declared riichi, measured over Tenhou houou four-player
// hanchan logs.
//
//   source   https://github.com/chienshyong/houou-statistics/blob/80dc535dc7eab1a0faf18a2fbcfe72db2067976a/results/WaitDistribution.csv
//   commit   80dc535dc7eab1a0faf18a2fbcfe72db2067976a (2023-11-25)
//   upstream forked from https://github.com/Euophrys/houou-analysis (MIT). No code is copied here, only
//            aggregate counts, which are measured facts rather than expression.
//   fetched  2026-08-27
//
// The sample is 142,461 riichi tenpai hands (182,490 open), NOT the full
// 893,440-game database: upstream's `rowcount` caps how many logs an analyzer reads.
// 4,894 riichi hands held a wait too complex for the analyzer to enumerate and are
// absent from these tables — kokushi is one of them, which is why its prior is a stated constant
// in `dealIn.ts` rather than a figure here.
//
// Index 0 is honours and 1-9 are ranks within a numbered suit. Counts are aggregated across the
// three numbered suits (or the seven honour kinds), so `dealIn.ts` divides a bucket by the number
// of hypotheses sharing it. Every shape is indexed by the lowest tile it waits on; the extraction
// script records the three caveats that convention carries.
import type { ShapePrior } from './dealIn'

/** The block `dealInRisk` reads: the model only ever speaks about a seat that has declared. */
export const HOUOU_PRIOR: ShapePrior = {
  name: 'houou',
  kind: 'measured',
  weights: {
    sanmenchan: [0, 2735, 2756, 2682, 0, 0, 0, 0, 0, 0],
    ryanmen: [0, 11177, 12740, 14199, 14012, 12688, 11392, 0, 0, 0],
    penchan: [0, 0, 0, 3237, 0, 0, 0, 3349, 0, 0],
    kanchan: [0, 0, 3604, 3646, 3004, 2489, 2968, 3737, 3720, 0],
    tanki: [3311, 734, 595, 620, 232, 639, 225, 650, 647, 712],
  },
  shanpon: [
    [599, 709, 710, 619, 604, 722, 610, 597, 730, 712],
    [0, 81, 278, 220, 189, 254, 183, 196, 254, 290],
    [0, 0, 96, 256, 239, 234, 191, 222, 251, 232],
    [0, 0, 0, 55, 201, 198, 127, 161, 190, 190],
    [0, 0, 0, 0, 32, 236, 141, 134, 177, 195],
    [0, 0, 0, 0, 0, 55, 243, 184, 249, 259],
    [0, 0, 0, 0, 0, 0, 31, 196, 235, 194],
    [0, 0, 0, 0, 0, 0, 0, 61, 282, 236],
    [0, 0, 0, 0, 0, 0, 0, 0, 99, 310],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 118],
  ],
}

/** Open tenpai, whose shape mix is materially different — far more kanchan and shanpon, far fewer
 *  ryanmen. Nothing reads it yet: `ThreatView` does not say whether a seat has melded, and the
 *  model refuses to speak about undeclared seats at all (plans/EV-2 §2). Extracted because the
 *  same parse produces it, and because using the riichi block against a melded threat is one of
 *  the known wrongnesses (plans/EV-5 §1.10). */
export const HOUOU_OPEN_PRIOR: ShapePrior = {
  name: 'houou-open',
  kind: 'measured',
  weights: {
    sanmenchan: [0, 1234, 1406, 1213, 0, 0, 0, 0, 0, 0],
    ryanmen: [0, 9232, 13654, 16237, 16088, 13727, 9175, 0, 0, 0],
    penchan: [0, 0, 0, 4254, 0, 0, 0, 4328, 0, 0],
    kanchan: [0, 0, 4315, 6482, 6363, 5465, 6241, 6727, 4358, 0],
    tanki: [2879, 810, 1117, 1160, 881, 1323, 911, 1146, 1176, 832],
  },
  shanpon: [
    [2370, 1544, 1444, 1320, 1434, 1790, 1485, 1277, 1482, 1563],
    [0, 113, 316, 284, 267, 351, 274, 270, 295, 316],
    [0, 0, 246, 658, 689, 729, 579, 646, 773, 279],
    [0, 0, 0, 182, 589, 662, 576, 511, 654, 273],
    [0, 0, 0, 0, 156, 653, 562, 586, 613, 297],
    [0, 0, 0, 0, 0, 195, 669, 660, 735, 371],
    [0, 0, 0, 0, 0, 0, 166, 589, 701, 288],
    [0, 0, 0, 0, 0, 0, 0, 169, 618, 299],
    [0, 0, 0, 0, 0, 0, 0, 0, 244, 325],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 82],
  ],
}

/** What the source file says about itself, and what the riichi tables above imply. `width` is the
 *  expected number of distinct tile kinds a riichi waits on. */
export const HOUOU_PRIOR_META = {
  riichiHands: 142461,
  complexWaits: 4894,
  enumeratedHands: 137567,
  /** Mean ukeire in TILES, straight from the file — the same fact as `width`, at ~3.6 unseen
   *  copies per kind. */
  reportedWidthInTiles: 6.409887618,
  width: 1.7823169800897019,
  /** P(a riichi waits on SOME tile of this rank), index 1-9, measured by a different analyzer over
   *  the same database (`results/DorasobaDanger.csv`). Index 0 is unused: the honour buckets there overlap
   *  in a way the analyzer does not document. Divide by three for one specific tile. */
  waitByRank: [
    0.0, 0.123013, 0.176435, 0.214472, 0.236693, 0.259276, 0.242748, 0.213208, 0.165195, 0.109451,
  ],
} as const
