// GENERATED by scripts/build-ev-models.mjs — do not edit by hand.
//
// The measured half of the houou EV model: wait-shape counts for a seat that has declared riichi,
// what giving up on a hand costs, and what a riichi hand pays — all over Tenhou houou four-player
// hanchan logs.
//
//   source   https://github.com/chienshyong/houou-statistics/blob/80dc535dc7eab1a0faf18a2fbcfe72db2067976a/results/WaitDistribution.csv
//            https://github.com/chienshyong/houou-statistics/blob/80dc535dc7eab1a0faf18a2fbcfe72db2067976a/results/BetaoirCost.csv
//            https://github.com/chienshyong/houou-statistics/blob/80dc535dc7eab1a0faf18a2fbcfe72db2067976a/results/HandScore.csv
//   commit   80dc535dc7eab1a0faf18a2fbcfe72db2067976a (2023-11-25)
//   upstream forked from https://github.com/Euophrys/houou-analysis (MIT). No code is copied here, only
//            aggregate counts, which are measured facts rather than expression.
//   fetched  2026-08-27
//
// The sample is 142,461 riichi tenpai hands (182,490 open), NOT the full
// 893,440-game database: upstream's `rowcount` caps how many logs an analyzer reads.
// 4,894 riichi hands held a wait too complex for the analyzer to enumerate and are
// absent from these tables — kokushi is one of them, which is why its prior is a stated constant
// in `dealIn.ts` rather than a figure here.
//
// Index 0 is honours and 1-9 are ranks within a numbered suit. Counts are aggregated across the
// three numbered suits (or the seven honour kinds), so `dealIn.ts` divides a bucket by the number
// of hypotheses sharing it. Every shape is indexed by the lowest tile it waits on; the extraction
// script records the three caveats that convention carries.
import type { ShapePrior } from './dealIn'

/** The block `dealInRisk` reads: the model only ever speaks about a seat that has declared. */
export const HOUOU_PRIOR: ShapePrior = {
  name: 'houou',
  kind: 'measured',
  weights: {
    sanmenchan: [0, 2735, 2756, 2682, 0, 0, 0, 0, 0, 0],
    ryanmen: [0, 11177, 12740, 14199, 14012, 12688, 11392, 0, 0, 0],
    penchan: [0, 0, 0, 3237, 0, 0, 0, 3349, 0, 0],
    kanchan: [0, 0, 3604, 3646, 3004, 2489, 2968, 3737, 3720, 0],
    tanki: [3311, 734, 595, 620, 232, 639, 225, 650, 647, 712],
  },
  shanpon: [
    [599, 709, 710, 619, 604, 722, 610, 597, 730, 712],
    [0, 81, 278, 220, 189, 254, 183, 196, 254, 290],
    [0, 0, 96, 256, 239, 234, 191, 222, 251, 232],
    [0, 0, 0, 55, 201, 198, 127, 161, 190, 190],
    [0, 0, 0, 0, 32, 236, 141, 134, 177, 195],
    [0, 0, 0, 0, 0, 55, 243, 184, 249, 259],
    [0, 0, 0, 0, 0, 0, 31, 196, 235, 194],
    [0, 0, 0, 0, 0, 0, 0, 61, 282, 236],
    [0, 0, 0, 0, 0, 0, 0, 0, 99, 310],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 118],
  ],
}

/** Open tenpai, whose shape mix is materially different — far more kanchan and shanpon, far fewer
 *  ryanmen. Nothing reads it yet: `ThreatView` does not say whether a seat has melded, and the
 *  model refuses to speak about undeclared seats at all (plans/EV-2 §2). Extracted because the
 *  same parse produces it, and because using the riichi block against a melded threat is one of
 *  the known wrongnesses (plans/EV-5 §1.10). */
export const HOUOU_OPEN_PRIOR: ShapePrior = {
  name: 'houou-open',
  kind: 'measured',
  weights: {
    sanmenchan: [0, 1234, 1406, 1213, 0, 0, 0, 0, 0, 0],
    ryanmen: [0, 9232, 13654, 16237, 16088, 13727, 9175, 0, 0, 0],
    penchan: [0, 0, 0, 4254, 0, 0, 0, 4328, 0, 0],
    kanchan: [0, 0, 4315, 6482, 6363, 5465, 6241, 6727, 4358, 0],
    tanki: [2879, 810, 1117, 1160, 881, 1323, 911, 1146, 1176, 832],
  },
  shanpon: [
    [2370, 1544, 1444, 1320, 1434, 1790, 1485, 1277, 1482, 1563],
    [0, 113, 316, 284, 267, 351, 274, 270, 295, 316],
    [0, 0, 246, 658, 689, 729, 579, 646, 773, 279],
    [0, 0, 0, 182, 589, 662, 576, 511, 654, 273],
    [0, 0, 0, 0, 156, 653, 562, 586, 613, 297],
    [0, 0, 0, 0, 0, 195, 669, 660, 735, 371],
    [0, 0, 0, 0, 0, 0, 166, 589, 701, 288],
    [0, 0, 0, 0, 0, 0, 0, 169, 618, 299],
    [0, 0, 0, 0, 0, 0, 0, 0, 244, 325],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 82],
  ],
}

/**
 * What it costs to give up on a hand while somebody is in riichi: points, by the turn you are
 * deciding on and by who is threatening whom.
 *
 * Keys are `me vs each threat`, D for dealer and ND for not, threats in the order upstream writes
 * them (the dealer first when one of them is the dealer). Values are per entry of `turns`, and
 * negative — they are losses.
 *
 * **This is not the whole fold price.** The measurement excludes every seat that dealt in, so what
 * is here is opponents' tsumo payments plus the noten penalty, and nothing else. Add the deal-in
 * term to it: `EV(fold) = HOUOU_FOLD_COST + P(deal in while folding) × HOUOU_HAND_SCORE.ron`.
 *
 * `samples` is the hand count behind each cell. Some are tiny — two hands in one turn-4 cell — so
 * a reader of this table must check them before believing a number.
 *
 * source `analyzers/betaori_cost.py`, units converted from Tenhou score deltas (hundreds) to
 * points at extraction.
 */
export const HOUOU_FOLD_COST = {
  turns: [4, 6, 8, 10, 12, 14, 16, 18],
  cost: {
    'D vs ND': [-1952, -1925, -1886, -1852, -1788, -1667, -1447, -1479],
    'ND vs ND': [-1092, -1107, -1124, -1154, -1186, -1226, -1253, -1395],
    'ND vs D': [-1869, -1795, -1746, -1676, -1622, -1518, -1361, -1373],
    'D vs ND ND': [-1903, -1754, -1709, -1768, -1791, -1800, -1735, -2178],
    'ND vs ND ND': [-980, -940, -933, -997, -1093, -1230, -1475, -1854],
    'ND vs D ND': [-1238, -1321, -1297, -1318, -1384, -1447, -1558, -1668],
    'D vs ND ND ND': [0, -1892, -1557, -1129, -1689, -2139, -2320, null],
    'ND vs D ND ND': [0, -687, -799, -948, -869, -1084, -1889, -2000],
  },
  samples: {
    'D vs ND': [18171, 42200, 61088, 63417, 53781, 40725, 29319, 2903],
    'ND vs ND': [39983, 92352, 132446, 137373, 115841, 87435, 62429, 5563],
    'ND vs D': [30115, 66526, 95225, 100617, 87485, 68126, 51523, 6556],
    'D vs ND ND': [320, 1732, 4463, 6819, 7183, 5784, 3683, 100],
    'ND vs ND ND': [334, 1784, 4637, 7031, 7368, 5925, 3762, 82],
    'ND vs D ND': [776, 4495, 11728, 18162, 19694, 15891, 10520, 492],
    'D vs ND ND ND': [2, 12, 61, 111, 142, 109, 61, 0],
    'ND vs D ND ND': [3, 45, 176, 415, 491, 399, 196, 3],
  },
} as const

/**
 * What a riichi hand pays when it wins, by the turn it declared — the deal-in cost `plans/EV-3` §4
 * calls `value_j`, conditioned by the threat's dealership as that section's option 2 asks for.
 *
 * Points as scored: riichi and honba sticks are excluded upstream, yakuman are excluded upstream,
 * and ura and dora are included because these are real wins off real logs rather than a shape
 * priced by a scorer. `ron` is what the discarder pays. `tsumo` is the winner's whole take before
 * the three-way split, so a payer's share is arithmetic on top of it, not a figure in this table.
 *
 * Indexed by turn 0-18 directly. The early turns are thin — check `ronSamples`.
 *
 * source `analyzers/hand_score.py`.
 */
export const HOUOU_HAND_SCORE = {
  dealer: {
    ron: [10900, 6944, 7012, 6994, 7114, 7248, 7350, 7473, 7581, 7775, 7946, 8136, 8371, 8491, 8777, 9060, 9150, 9430, 14000],
    tsumo: [13767, 9552, 9548, 9660, 9791, 9859, 10005, 10078, 10184, 10394, 10484, 10745, 10831, 11099, 11288, 11522, 12133, 11106, 8475],
    ronSamples: [4, 2230, 5595, 10342, 16283, 22150, 25990, 27148, 25320, 21638, 16842, 12325, 8201, 5163, 2857, 1276, 448, 70, 3],
    tsumoSamples: [9, 2729, 6979, 13279, 20643, 27193, 30634, 31222, 28274, 23316, 17817, 12797, 8095, 4948, 2602, 1127, 289, 47, 4],
    damaRon: [8142, 8485, 7936, 7557, 7325, 7515, 7495, 7495, 7532, 7421, 7491, 7450, 7444, 7525, 7755, 7722, 7753, 8145, 8597],
    damaRonSamples: [12, 167, 448, 1077, 2123, 3767, 5909, 7900, 9495, 10794, 11004, 10244, 9421, 7959, 6476, 5166, 4008, 2572, 549],
  },
  nonDealer: {
    ron: [5106, 4827, 4855, 4911, 4986, 5099, 5202, 5289, 5423, 5554, 5685, 5805, 5985, 6034, 6320, 6580, 6658, 7340, 6600],
    tsumo: [6652, 6535, 6640, 6673, 6816, 6873, 6959, 7071, 7218, 7322, 7428, 7592, 7776, 7999, 8125, 8568, 8933, 9456, 10633],
    ronSamples: [293, 7109, 17094, 32009, 47991, 61663, 70140, 69652, 62183, 51121, 38788, 27238, 17617, 10349, 5210, 2045, 464, 40, 3],
    tsumoSamples: [263, 6934, 16943, 31390, 47835, 61031, 67728, 65851, 57813, 46622, 34541, 23851, 14886, 8564, 4007, 1458, 283, 9, 3],
    damaRon: [3743, 4752, 4763, 4241, 4136, 4137, 4144, 4156, 4213, 4304, 4339, 4420, 4536, 4652, 4790, 4826, 4916, 5193, 5483],
    damaRonSamples: [40, 262, 1122, 2623, 5759, 10934, 17637, 24694, 30450, 34419, 34758, 33392, 29810, 24903, 20507, 16279, 12622, 8290, 1688],
  },
} as const

/** What the source file says about itself, and what the riichi tables above imply. `width` is the
 *  expected number of distinct tile kinds a riichi waits on. */
export const HOUOU_PRIOR_META = {
  riichiHands: 142461,
  complexWaits: 4894,
  enumeratedHands: 137567,
  /** Mean ukeire in TILES, straight from the file — the same fact as `width`, at ~3.6 unseen
   *  copies per kind. */
  reportedWidthInTiles: 6.409887618,
  width: 1.7823169800897019,
  /** P(a riichi waits on SOME tile of this rank), index 1-9, measured by a different analyzer over
   *  the same database (`results/DorasobaDanger.csv`). Index 0 is unused: the honour buckets there overlap
   *  in a way the analyzer does not document. Divide by three for one specific tile. */
  waitByRank: [0.000000, 0.123013, 0.176435, 0.214472, 0.236693, 0.259276, 0.242748, 0.213208, 0.165195, 0.109451],
} as const
